name: Test github actions

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{ github.workspace}}:/container
      options: --cpus 1

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
      - name: Open the backend and Install dependencies
        run: cd container & npm i
      - name: Build the image
        run: docker build -t my-node-app .